# Default values for spring-petclinic-backend.

replicaCount: 1

image:
  repository: 038062473746.dkr.ecr.us-east-1.amazonaws.com/team-github-action/spring-petclinic-backend
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80

resources: {}

