# Default values for spring-petclinic-backend.

replicaCount: 1

image:
  #TODO: need to fixed the image upload issue for team-github-action/spring-petclinic-backend
  repository:  038062473746.dkr.ecr.us-east-1.amazonaws.com/harness-petclinic-backend
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80

resources: {}

