# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Spring-Petclinic-Backend-CICD

on:
  push:
    branches: [ dockerized-backend ]
  pull_request:
    branches: [ dockerized-backend ]

jobs:
  ci-cd:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
#       - name: Set up JDK 1.8
#         uses: actions/setup-java@v1
#         with:
#           java-version: 1.8
#       - name: Cache Maven packages
#         uses: actions/cache@v2
#         with:
#           path: ~/.m2
#           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
#           restore-keys: ${{ runner.os }}-m2
#       - name: Run Test
#         run: ./mvnw clean test
#       - name: Build
#         run: ./mvnw clean -B package --file pom.xml -Dmaven.test.skip=true
#       - name: Docker Build and Push
#         uses: kciter/aws-ecr-action@master
#         with:
#           access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           account_id: ${{ secrets.AWS_ACCOUNT_ID }}
#           repo: team-github-action/spring-petclinic-backend
#           region: us-east-1
#           tags: latest,${{ github.sha }}
#           create_repo: true
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: check-aws
        run: kubectl version #aws eks update-kubeconfig --region us-east-1 --name basic-cluster --role-arn arn:aws:iam::038062473746:role/CICDHackathon
#       - name: helm deploy
#         uses: koslibpro/helm-eks-action@master
#         with:
#           command: helm status spring-petclinic-backend -n github-action #helm upgrade spring-petclinic-backend --install --wait spring-petclinic-frontend/ -f configuration/values.dev.yaml

