# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master, dockerized-backend ]
  pull_request:
    branches: [ master, dockerized-backend ]

jobs:
  test-and-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Run Test
      run: ./mvnw clean test
    - name: Build
    - run: ./mvnw clean -B package --file pom.xml -Dmaven.test.skip=true
    - uses: actions/upload-artifact@master
      with:
        name: app.jar
        path: target/spring-petclinic-backend-*.jar
        
  build-and-push-docker-image:
    
    runs-on: ubuntu-latest
    
    needs: [test-and-build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: app.jar
          path: target/spring-petclinic-backend-*.jar
      - name: Docker Build and Push
        uses: kciter/aws-ecr-action@master
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: team-github-action/spring-petclinic-backend
          region: us-east-1
          tags: latest,${{ github.sha }}
          create_repo: true 
