name: Spring-Petclinic-Backend-CICD

on:
  push:
    branches: [ dockerized-backend ]
  pull_request:
    branches: [ dockerized-backend ]

jobs:
  ci-cd:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Test
        run: ./mvnw clean test
      - name: Build
        run: ./mvnw clean -B package --file pom.xml -Dmaven.test.skip=true
      - name: Docker Build and Push
        uses: kciter/aws-ecr-action@master
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          repo: team-github-action/petclinic-backend
          region: us-east-1
          tags: latest,${{ github.sha }}
          create_repo: true
      - name:  Configure-AWS-Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: helm-deploy-staging
        uses: koslibpro/helm-eks-action@master
        env:  
            KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          command: helm upgrade spring-petclinic-backend --namespace github-action-staging --create-namespace --install --wait spring-petclinic-backend/ -f configuration/values.staging.yaml

      - name: helm-deploy-production
        uses: koslibpro/helm-eks-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          command: helm upgrade spring-petclinic-backend --namespace github-action-production --create-namespace --install --wait spring-petclinic-backend/ -f configuration/values.production.yaml

